---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-pipeline-run
spec:
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
  params:
    - name: repo-url
      value: "https://github.com/kb1278/ci-cd-final-project.git"
    - name: app-name
      value: "ci-cd-app"
    - name: build-image
      value: "image-registry.openshift-image-registry.svc:5000/sn-labs-bhamra1234/ci-cd-app:latest"
