apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
    - name: app-name
      type: string
    - name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: output

    - name: flake8-lint
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: nose-tests
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: build-image
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: $(params.build-image)

    - name: deploy
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e
            echo "Deploying app $(params.app-name) with image $(params.build-image)"
            oc create deployment "$(params.app-name)" --image="$(params.build-image)" --dry-run=client -o yaml | oc apply -f -
